"""One-time: hash the sheet companies' own passwords (BACKEND_CONTRACT.md v1.7 section 7c Login, DECISIONS.md #41).

Reads the Login Credentials tab of a LOCAL copy of the workbook that still has its temporary passwords (the
committed copy has them removed) and writes backend/seed/source/sheet_password_hashes.json with, per company:
  passwordHash  PBKDF2-SHA256 with a random salt: what login checks
  fingerprint   SHA-256 of the password: lets test_sheet_passwords prove that no sheet password appears
                anywhere in the repository without the repository ever holding one (the passwords are
                16 random characters, so neither value can be turned back into a password)
The plaintext is never written anywhere. Run again only if the sheet's passwords change:

    python backend/seed/hash_sheet_passwords.py "C:/path/to/workbook with passwords.xlsx"
"""

import hashlib
import json
import sys
from pathlib import Path

import openpyxl

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))
from services.passwords import hash_password  # noqa: E402

OUT = BACKEND / "seed" / "source" / "sheet_password_hashes.json"


def sheet_logins(path: str) -> list[dict]:
    """The Login Credentials rows (Company ID, Company, Login Email, Temporary Password)."""
    rows = list(openpyxl.load_workbook(path, read_only=True, data_only=True)["Login Credentials"].iter_rows(values_only=True))
    hi = next(i for i, r in enumerate(rows) if r and "Login Email" in r)
    header = rows[hi]
    col = {name: next(j for j, h in enumerate(header) if h == name) for name in ("Company ID", "Company", "Login Email")}
    col["Temporary Password"] = next(j for j, h in enumerate(header) if h and str(h).startswith("Temporary Password"))
    return [{k: r[j] for k, j in col.items()} for r in rows[hi + 1:] if r and str(r[0] or "").startswith("CO-")]


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    logins = sheet_logins(sys.argv[1])
    missing = [r["Company"] for r in logins if not r["Temporary Password"]]
    if len(logins) != 150 or missing:
        sys.exit(f"Expected 150 companies with passwords; got {len(logins)}, missing {len(missing)}. "
                 "Use the local workbook that still has its temporary passwords.")
    accounts = [{"companyId": r["Company ID"], "company": r["Company"], "loginEmail": r["Login Email"].strip().lower(),
                 "passwordHash": hash_password(str(r["Temporary Password"])),
                 "fingerprint": hashlib.sha256(str(r["Temporary Password"]).encode()).hexdigest()}
                for r in logins]
    body = {"about": "Hashes of the sheet companies' own passwords (contract v1.7 section 7c, decision #41). "
                     "No plaintext. Generated by seed/hash_sheet_passwords.py from a local copy of the sheet.",
            "accounts": accounts}
    text = json.dumps(body, indent=2) + "\n"
    assert not any(str(r["Temporary Password"]) in text for r in logins)  # belt and braces
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {len(accounts)} hashes to {OUT.relative_to(BACKEND.parent)} (no plaintext).")


if __name__ == "__main__":
    main()
